### ISSUE TITLE
Measurement / MeasurementType Interface

### ISSUE THREAD

**Issue by benreyn** [rubyforgood/abalone#308]
An organization needs to define an acceptable list of measurement names and measurement value types for measurements that will be added to the system. This will most likely take the form of an interface exposed at the organization level.

Examples:
```
Measurement Name: Length
Measurement Value Type: Centimeters

Measurement Name: Age
Measurement Value Type: Days

Measurement Name: Weight
Measurement Value Type: Grams

Measurement Name: Quantity
Measurement Value Type: Units
```

The current structure of the Measurement model points to an approach where the acceptable measurement names and measurement value types are configured for the organization and then used to validate measurements as they are accepted into the system.

An alternative approach being considered is to add a MeasurementType model with the name, value type and an organization_id. A Measurement belongs_to a MeasurementType and a MeasurementType has_many measurements. A MeasurementType belongs_to an organization and an Organization has_many measurement types. The acceptable list would be the MeasurementType records for an organization and those would be used for Measurements being accepted into the system.

#### Tasks: 

Note: These are broad and can be broken out into individual issues

- [x] Determine an approach
- [x] Add the MeasurementType model and relationships, if going with this approach
- [x] Update the relevant seed files, factories and specs
- [x] Build out the interface for defining these values at the organization level.

Note: The concept of an "organization level" means that an admin user for an organization would be defining these values. If this issue is addressed before #338, this concept can be ignored with the understanding that we would scope that level of access once #338 has been completed.

**Comment by todtb** [comment]
> An alternative approach being considered is to add a MeasurementType model with the name, value type and an organization_id

This 100% makes sense to me, especially when considering end users will be managing the creation of these annotations.

A few notes:

1) If the `MeasurementTypes` belongs_to an organization through an `organization_id`, we'll likely end up with multiple `MeasurementTypes` for the common ones such as length, weight, etc. Not a huge issue, but we'd want to make sure these couldn't be duplicated WITHIN the organization. Thus we'd want some sort of composite uniqueness constraint such as:
    ```sql
    CREATE UNIQUE INDEX name_unit_organization_id 
    ON measurement_types (name, unit, organization_id)
    ```
1) Should this be for all three fields? I imagine given the user base this is all SI, and you wouldn't want two measurement types with the same name, alternate units such as MeasurementType: { name: "length", unit: "cm" } and  MeasurementType: { name: "length", unit: "in" }

What are your thoughts @wadewinningham?

**Comment by wadewinningham** [comment]
Is the intent to keep each organizations data/reporting separate, or to normalize the data so you can eventually get reports/charts across all organizations?

**Comment by benreyn** [comment]
> eventually get reports/charts across all organizations?

There are no plans for this at this time no, and I think its safe to assume that we will not. I'm guessing that your concerned about the need for an organization agnostic `canonical measurement type` @wadewinningham ?

@CraigJZ Do you think this is correct re: not wanting to do cross organization reporting?

**Comment by CraigJZ** [comment]
Yes, that's correct. I'd agree with @benreyn that it would be safe to assume that wouldn't be needed in the near future.

**Comment by wadewinningham** [comment]
In that case, I think what you have specified is fine and doesn't box you in too much. You could change and convert data down the road if you really need to.

My main concern would be with reports and charts being distinct per organization. But maybe that's anticipated. I'm sure you'll look towards sharing code as much as possible, though.
